### ISSUE TITLE
fall back to formatting entire document outside of git repos or when lsp doesn't support range formatting

### ISSUE THREAD

**Issue by bagel897** [joechrisellis/lsp-format-modifications.nvim#4]
Add an option to do this

**Comment by joechrisellis** [comment]
This is a good shout, I'll implement this when I have some time free.

**Comment by joechrisellis** [comment]
Had a chance to think more about this today. Here's my current stance.

- Fall back to formatting

**Comment by joechrisellis** [comment]
@bagel897 

Had a chance to think more about this today. My current view: I’m against adding new options, but all for changing the API to enable these uses. For this kind of workflow it's better to step away from the `attach` style of setup (which is for convenience really) and take things more into your own hands. I'm actually in two minds whether or not to deprecate the whole `attach` dance (`:FormatModifications` command included, since its semantics _can_ be unintuitive) and guide folks toward the "hard way" (with a bunch of example setups).

To address the issue direct: there are two separate asks here, and both can be solved with the same solution. Here’s what I think would work:

* Change the core API functions so that they return a boolean indicating success. If the LSP server doesn't support range formatting, or we're outside of a Git repository, it'll be signalled by a `false` return value.
* You can inspect this result and decide what to do of your own accord. I.e. if we fail, you can fall back to full-document formatting, abort entirely, or do something else -- but the logic will live in your config. I think this beats adding _specific_ fallback options to the plugin.

A future 'blessed configuration' would look like this:

```lua
local on_attach = function(client, bufnr)
  -- your usual configuration — options, keymaps, etc
  -- ...

  -- setup autocmd to format modifications on save
  local augroup_id = vim.api.nvim_create_augroup(
    "NvimFormatModificationsDocumentFormattingGroup",
    { clear = false }
  )
  vim.api.nvim_clear_autocmds({ group = augroup_id, buffer = bufnr })

  vim.api.nvim_create_autocmd(
    { "BufWritePre" },
    {
      group = augroup_id,
      buffer = bufnr,
      callback = function()
        local lsp_format_modifications = require"lsp-format-modifications"
        local success = lsp_format_modifications.format_modifications(client, bufnr, {})
        if not success then -- e.g. not in a git repository, range formatting not supported, ...
          vim.lsp.buf.format{bufnr = bufnr} -- fallback to full-buffer formatting
        end
      end,
    }
  )
end
```

I don't think this setup -- _without_ the `attach` function -- is hard to grok. And it's a lot more flexible.

I have some local changes for this. I'll push these shortly as a PR and request your review?

**Comment by joechrisellis** [comment]
@bagel897

I'd value your opinion on [this PR](https://github.com/joechrisellis/lsp-format-modifications.nvim/pull/7), time permitting! It's small. I'll probably merge in the next few days otherwise. 😄

**Comment by bagel897** [comment]
I don't really use neovim right now, sorry.  Couldn't we use the LspAttach event to do this instead of on_attach?
Thanks for your consideration

**Comment by jellis206** [comment]
This would be awesome! I can review it for you. I don't have a ton of experience writing plugins, but I am really interested in getting something like this setup in my nvim config, so anything to help that along!

**Comment by joechrisellis** [comment]
This is now possible (#7). Something like:

```lua
local on_attach = function(client, bufnr)
  -- your usual configuration — options, keymaps, etc
  -- ...

  local augroup_id = vim.api.nvim_create_augroup(
    "FormatModificationsDocumentFormattingGroup",
    { clear = false }
  )
  vim.api.nvim_clear_autocmds({ group = augroup_id, buffer = bufnr })

  vim.api.nvim_create_autocmd(
    { "BufWritePre" },
    {
      group = augroup_id,
      buffer = bufnr,
      callback = function()
        local lsp_format_modifications = require "lsp-format-modifications"
        local result = lsp_format_modifications.format_modifications(client, bufnr)
        if not result.success then -- fall back to full-document formatting
          vim.lsp.buf.format {
            id = client.id,
            bufnr = bufnr,
          }
        end
      end,
    }
  )
end
```

... should work for formatting modifications on save, falling back to full-document formatting if unsuccessful.

Note this isn't perfect; if we return `{ success = false }` for something unexpected/"weird" like not being able to find the comparee, this will format the whole document. I'm contemplating how best to solve this -- perhaps adding more detail to the value returned from `require"lsp-format-modifications".format_modifications`.
